### ISSUE TITLE
requirements elicitation

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2022-FMFI/personalaccount#1]
example of export from SAP
[priklad_M fond 2.txt](https://github.com/TIS2022-FMFI/personalaccount/files/10021908/priklad_M.fond.2.txt)
[priklad_M fond.zip](https://github.com/TIS2022-FMFI/personalaccount/files/10021909/priklad_M.fond.zip)

**Comment by pavelpetrovic** [comment]
first collection of requirements
[account_requirements.txt](https://github.com/TIS2022-FMFI/personalaccount/files/10022196/account_requirements.txt)

**Comment by mousetom-sk** [comment]
done
