### ISSUE TITLE
spísať katalóg požiadaviek

### ISSUE THREAD

**Issue by k00cur1k** [TIS2022-FMFI/personalaccount#2]

**Comment by jakloo** [comment]
[katalóg požiadaviek](https://docs.google.com/document/d/1e2vD9EISczK2EEgzJevroAaOxMguqtB9/edit?usp=drivesdk&ouid=113560403810466940979&rtpof=true&sd=true)

**Comment by mousetom-sk** [comment]
nová verzia Katalógu požiadaviek je dostupná na Google Disku (zostáva doplniť sekciu 2.4)

**Comment by mousetom-sk** [comment]
pripomienky zadávateľa boli zapracované, nová verzia je na Google Disku

**Comment by mousetom-sk** [comment]
dokončené
