### ISSUE TITLE
návrh grafického rozhrania

### ISSUE THREAD

**Issue by mousetom-sk** [TIS2022-FMFI/personalaccount#3]

**Comment by jakloo** [comment]
[Prototyp základných obrazoviek aplikácie](https://www.figma.com/proto/aCfjjDmQMJXR2jaMNrwJgw/Untitled?node-id=0%3A3&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=0%3A3)

**Comment by jakloo** [comment]
Pôvodné nákresy GUI sú v dokumente [Návrh](https://docs.google.com/document/d/1R1XwvvAJX__KLI8sA3kpQIulvbJ33Qb6/edit?usp=drivesdk&ouid=113560403810466940979&rtpof=true&sd=true)

**Comment by mousetom-sk** [comment]
hotovo
