### ISSUE TITLE
návrh perzistentnej vrstvy

### ISSUE THREAD

**Issue by mousetom-sk** [TIS2022-FMFI/personalaccount#5]

**Comment by Granko15** [comment]
Návrh perzistentnej vrstvy na linku:
https://drive.google.com/file/d/11VlOhWdXybh3w1iZGQ1NELUWK6RY5o3r/view?usp=drivesdk

**Comment by mousetom-sk** [comment]
Bola navrhnutá organizácia SAP reportov nahrávaných používateľmi

**Comment by mousetom-sk** [comment]
dokončené - prípadné drobné zmeny už len podľa potreby pri implementácií
