### ISSUE TITLE
návrh formátu exportov

### ISSUE THREAD

**Issue by mousetom-sk** [TIS2022-FMFI/personalaccount#6]

**Comment by Granko15** [comment]
Návrh formátu exportu operácií na linku:
https://drive.google.com/file/d/1eudWem2ZZB9P9JPY0nWAAe9-csqiPIbb/view?usp=drivesdk

**Comment by mousetom-sk** [comment]
dokončené - prípadné drobné zmeny už len podľa potreby pri implementácií
